/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.swing.swingdemo;

import javax.swing.JOptionPane;

/**
 *
 * @author chung
 */
public class OptionPaneDialogFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptionPaneDialog
     */
    public OptionPaneDialogFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowAlertDialog = new javax.swing.JButton();
        btnShowWarningDialog = new javax.swing.JButton();
        btnShowInputDialog = new javax.swing.JButton();
        btnCornfirmDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnShowAlertDialog.setText("Show Alert Dialog");
        btnShowAlertDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAlertDialogActionPerformed(evt);
            }
        });

        btnShowWarningDialog.setText("Show Warning Dialog");
        btnShowWarningDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowWarningDialogActionPerformed(evt);
            }
        });

        btnShowInputDialog.setText("Show Input text Dialog");
        btnShowInputDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowInputDialogActionPerformed(evt);
            }
        });

        btnCornfirmDialog.setText("Confirm Dialog");
        btnCornfirmDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCornfirmDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCornfirmDialog)
                    .addComponent(btnShowInputDialog)
                    .addComponent(btnShowWarningDialog)
                    .addComponent(btnShowAlertDialog))
                .addContainerGap(719, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnShowAlertDialog)
                .addGap(29, 29, 29)
                .addComponent(btnShowWarningDialog)
                .addGap(26, 26, 26)
                .addComponent(btnShowInputDialog)
                .addGap(18, 18, 18)
                .addComponent(btnCornfirmDialog)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAlertDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAlertDialogActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This is alert Dialog");
    }//GEN-LAST:event_btnShowAlertDialogActionPerformed

    private void btnShowWarningDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowWarningDialogActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "This is Warning Dialig", "Warning", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_btnShowWarningDialogActionPerformed

    private void btnShowInputDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowInputDialogActionPerformed
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog(this, "Enter your name", "Question", JOptionPane.QUESTION_MESSAGE);

        if (name == null) {
            JOptionPane.showMessageDialog(this, "Moi nhap thong tin");
        } else {
            JOptionPane.showMessageDialog(this, "da nhap thong tin:: " + name);

        }
    }//GEN-LAST:event_btnShowInputDialogActionPerformed

    private void btnCornfirmDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCornfirmDialogActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "ban co muon thoat chuong trinh khong")==JOptionPane.OK_OPTION) {
             System.out.println("close oke");
        }
    }//GEN-LAST:event_btnCornfirmDialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionPaneDialogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionPaneDialogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionPaneDialogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionPaneDialogFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionPaneDialogFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCornfirmDialog;
    private javax.swing.JButton btnShowAlertDialog;
    private javax.swing.JButton btnShowInputDialog;
    private javax.swing.JButton btnShowWarningDialog;
    // End of variables declaration//GEN-END:variables
}
